version: '3.9'

services:

  redis:
    image: bitnami/redis:latest
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=docker
    # volumes:
    #   - redis_data:/bitnami/redis/data

  postgres:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=shortlinks
    # volumes:
    #   - postgres_data:/bitnami/postgresql/data

# volumes:
#   redis_data:
#   postgres_data: